### ISSUE TITLE
AICSに移管

### ISSUE THREAD

**Issue by Katsuyuki-Karasawa** [AI-Creators-Society/stable-diffusion-webui-localization-ja_JP#103]
ToDo
- @kokohachi にAICSのforkを消してもらう
- [extensions](https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions) の変更PR
- etc

**Comment by Katsuyuki-Karasawa** [comment]
できるだけ問題リストアップしておきたい

**Comment by Kokohachi** [comment]
> @Kokohachi にAICSのforkを消してもらう

Done
